networks:
  net:

volumes:
  postgres-data:

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file: .env.local
    networks:
      - net
    ports:
      - "5432:5432"

  kafka:
    container_name: kafka
    hostname: kafka
    image: apache/kafka:3.9.0
    restart: always
    env_file: .env.local
    networks:
      - net
    ports:
      - "9092:9092"

  insurance-calculation-backend:
    container_name: insurance_calculation_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env.prod
    networks:
      - net
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_started
