volumes:
  postgres-data:


services:
  postgresql:
    container_name: postgresql
    image: postgres:15.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file: .env.local
    ports:
      - "5432:5432"

  kafka:
    container_name: kafka
    image: apache/kafka:3.9.0
    restart: always
    env_file: .env.local
    ports:
      - "9092:9092"
